import React, { useState, useEffect } from 'react';
import { Container, Typography, Box, Card, CardContent, Grid, Button, ButtonGroup, Select, MenuItem, FormControl, InputLabel, SelectChangeEvent, Paper, CircularProgress, Alert } from '@mui/material';
import MoleculeViewer from '../../../components/features/molecules/MoleculeViewer';
import { load3DMol, getVisualizationStyles, getViewerSizePresets } from '../../../utils/moleculeViewerUtils';

// Sample PDB data for different molecules
const SAMPLE_MOLECULES = {
  caffeine: `COMPND    CAFFEINE
AUTHOR    GENERATED BY OPEN BABEL 3.1.0
HETATM    1  N   LIG     1       1.416   0.642   0.124  1.00  0.00           N
HETATM    2  C   LIG     1       0.776  -0.597   0.110  1.00  0.00           C
HETATM    3  N   LIG     1      -0.551  -0.874   0.057  1.00  0.00           N
HETATM    4  C   LIG     1      -1.608   0.041   0.011  1.00  0.00           C
HETATM    5  N   LIG     1      -1.468   1.370   0.013  1.00  0.00           N
HETATM    6  C   LIG     1      -0.235   1.914   0.061  1.00  0.00           C
HETATM    7  C   LIG     1       0.788   1.044   0.105  1.00  0.00           C
HETATM    8  O   LIG     1       1.483  -1.594   0.150  1.00  0.00           O
HETATM    9  O   LIG     1      -2.731  -0.438  -0.031  1.00  0.00           O
HETATM   10  C   LIG     1      -2.582   2.288  -0.031  1.00  0.00           C
HETATM   11  C   LIG     1      -0.088   3.410   0.062  1.00  0.00           C
HETATM   12  C   LIG     1      -0.651  -2.313   0.047  1.00  0.00           C
HETATM   13  C   LIG     1       2.865   0.765   0.184  1.00  0.00           C
HETATM   14  H   LIG     1      -2.228   3.320  -0.021  1.00  0.00           H
HETATM   15  H   LIG     1      -3.127   2.110   0.897  1.00  0.00           H
HETATM   16  H   LIG     1      -3.251   2.113  -0.879  1.00  0.00           H
HETATM   17  H   LIG     1       0.950   3.701   0.097  1.00  0.00           H
HETATM   18  H   LIG     1      -0.579   3.841  -0.819  1.00  0.00           H
HETATM   19  H   LIG     1      -0.572   3.841   0.947  1.00  0.00           H
HETATM   20  H   LIG     1      -1.700  -2.591   0.005  1.00  0.00           H
HETATM   21  H   LIG     1      -0.144  -2.743  -0.827  1.00  0.00           H
HETATM   22  H   LIG     1      -0.201  -2.750   0.951  1.00  0.00           H
HETATM   23  H   LIG     1       3.122   1.826   0.197  1.00  0.00           H
HETATM   24  H   LIG     1       3.296   0.280  -0.701  1.00  0.00           H
HETATM   25  H   LIG     1       3.321   0.294   1.069  1.00  0.00           H
CONECT    1    2    7   13
CONECT    2    1    3    8
CONECT    3    2    4   12
CONECT    4    3    5    9
CONECT    5    4    6   10
CONECT    6    5    7   11
CONECT    7    1    6
CONECT    8    2
CONECT    9    4
CONECT   10    5   14   15   16
CONECT   11    6   17   18   19
CONECT   12    3   20   21   22
CONECT   13    1   23   24   25
CONECT   14   10
CONECT   15   10
CONECT   16   10
CONECT   17   11
CONECT   18   11
CONECT   19   11
CONECT   20   12
CONECT   21   12
CONECT   22   12
CONECT   23   13
CONECT   24   13
CONECT   25   13
MASTER        0    0    0    0    0    0    0    0   25    0   25    0
END`,

  aspirin: `COMPND    ASPIRIN
AUTHOR    GENERATED BY OPEN BABEL 2.3.1
HETATM    1  C   LIG     1      -0.277   1.336   0.000  1.00  0.00           C
HETATM    2  C   LIG     1       1.023   0.830  -0.001  1.00  0.00           C
HETATM    3  C   LIG     1       1.234  -0.549  -0.001  1.00  0.00           C
HETATM    4  C   LIG     1       0.142  -1.423   0.000  1.00  0.00           C
HETATM    5  C   LIG     1      -1.158  -0.918   0.001  1.00  0.00           C
HETATM    6  C   LIG     1      -1.369   0.461   0.001  1.00  0.00           C
HETATM    7  C   LIG     1      -2.758   0.996   0.002  1.00  0.00           C
HETATM    8  O   LIG     1      -3.015   2.181   0.002  1.00  0.00           O
HETATM    9  O   LIG     1      -3.702   0.022   0.002  1.00  0.00           O
HETATM   10  C   LIG     1      -5.056   0.493   0.003  1.00  0.00           C
HETATM   11  C   LIG     1      -6.007  -0.673   0.003  1.00  0.00           C
HETATM   12  O   LIG     1      -5.710  -1.848   0.003  1.00  0.00           O
HETATM   13  O   LIG     1       2.528  -1.004  -0.002  1.00  0.00           O
HETATM   14  C   LIG     1       3.565  -0.072  -0.003  1.00  0.00           C
HETATM   15  O   LIG     1       4.718  -0.459  -0.003  1.00  0.00           O
HETATM   16  H   LIG     1      -0.440   2.406   0.000  1.00  0.00           H
HETATM   17  H   LIG     1       1.863   1.514  -0.002  1.00  0.00           H
HETATM   18  H   LIG     1       0.306  -2.493   0.000  1.00  0.00           H
HETATM   19  H   LIG     1      -1.998  -1.602   0.001  1.00  0.00           H
HETATM   20  H   LIG     1      -5.193   1.110   0.895  1.00  0.00           H
HETATM   21  H   LIG     1      -5.193   1.110  -0.889  1.00  0.00           H
HETATM   22  H   LIG     1      -7.056  -0.372   0.003  1.00  0.00           H
HETATM   23  H   LIG     1       3.318   0.988  -0.003  1.00  0.00           H
CONECT    1    2    6   16
CONECT    2    1    3   17
CONECT    3    2    4   13
CONECT    4    3    5   18
CONECT    5    4    6   19
CONECT    6    1    5    7
CONECT    7    6    8    9
CONECT    8    7
CONECT    9    7   10
CONECT   10    9   11   20   21
CONECT   11   10   12   22
CONECT   12   11
CONECT   13    3   14
CONECT   14   13   15   23
CONECT   15   14
CONECT   16    1
CONECT   17    2
CONECT   18    4
CONECT   19    5
CONECT   20   10
CONECT   21   10
CONECT   22   11
CONECT   23   14
MASTER        0    0    0    0    0    0    0    0   23    0   23    0
END`,

  ibuprofen: `COMPND    IBUPROFEN
AUTHOR    GENERATED BY OPEN BABEL 2.3.2
HETATM    1  C   LIG     1      -3.060  -1.349   0.267  1.00  0.00           C
HETATM    2  C   LIG     1      -1.765  -0.556   0.398  1.00  0.00           C
HETATM    3  C   LIG     1      -4.275  -0.416   0.236  1.00  0.00           C
HETATM    4  C   LIG     1      -0.583  -1.387   0.825  1.00  0.00           C
HETATM    5  C   LIG     1      -1.460   0.075  -0.952  1.00  0.00           C
HETATM    6  C   LIG     1      -1.857   0.554   1.472  1.00  0.00           C
HETATM    7  C   LIG     1       0.700  -0.601   0.937  1.00  0.00           C
HETATM    8  C   LIG     1       1.864  -1.141   0.410  1.00  0.00           C
HETATM    9  C   LIG     1       3.066  -0.426   0.507  1.00  0.00           C
HETATM   10  C   LIG     1       3.113   0.810   1.128  1.00  0.00           C
HETATM   11  C   LIG     1       1.965   1.345   1.676  1.00  0.00           C
HETATM   12  C   LIG     1       0.762   0.634   1.583  1.00  0.00           C
HETATM   13  C   LIG     1       4.323  -0.987  -0.088  1.00  0.00           C
HETATM   14  C   LIG     1       5.573  -0.174   0.182  1.00  0.00           C
HETATM   15  O   LIG     1       6.615  -0.609  -0.284  1.00  0.00           O
HETATM   16  O   LIG     1       5.459   0.958   0.889  1.00  0.00           O
HETATM   17  H   LIG     1      -3.177  -2.089  -0.530  1.00  0.00           H
HETATM   18  H   LIG     1      -3.000  -1.908   1.205  1.00  0.00           H
HETATM   19  H   LIG     1      -4.345   0.143   1.177  1.00  0.00           H
HETATM   20  H   LIG     1      -4.190   0.307  -0.580  1.00  0.00           H
HETATM   21  H   LIG     1      -5.202  -0.984   0.113  1.00  0.00           H
HETATM   22  H   LIG     1      -0.809  -1.846   1.795  1.00  0.00           H
HETATM   23  H   LIG     1      -0.404  -2.208   0.117  1.00  0.00           H
HETATM   24  H   LIG     1      -1.326  -0.688  -1.715  1.00  0.00           H
HETATM   25  H   LIG     1      -2.260   0.731  -1.294  1.00  0.00           H
HETATM   26  H   LIG     1      -0.549   0.677  -0.901  1.00  0.00           H
HETATM   27  H   LIG     1      -1.977   0.136   2.474  1.00  0.00           H
HETATM   28  H   LIG     1      -0.977   1.202   1.504  1.00  0.00           H
HETATM   29  H   LIG     1      -2.727   1.182   1.245  1.00  0.00           H
HETATM   30  H   LIG     1       1.836  -2.109  -0.074  1.00  0.00           H
HETATM   31  H   LIG     1       4.043   1.346   1.202  1.00  0.00           H
HETATM   32  H   LIG     1       2.003   2.300   2.188  1.00  0.00           H
HETATM   33  H   LIG     1      -0.117   1.061   2.041  1.00  0.00           H
HETATM   34  H   LIG     1       4.192  -1.067  -1.170  1.00  0.00           H
HETATM   35  H   LIG     1       4.479  -2.001   0.293  1.00  0.00           H
HETATM   36  H   LIG     1       6.243   1.434   1.085  1.00  0.00           H
CONECT    1    2    3   17   18
CONECT    2    1    4    5    6
CONECT    3    1   19   20   21
CONECT    4    2    7   22   23
CONECT    5    2   24   25   26
CONECT    6    2   27   28   29
CONECT    7    4    8   12
CONECT    8    7    9   30
CONECT    9    8   10   13
CONECT   10    9   11   31
CONECT   11   10   12   32
CONECT   12    7   11   33
CONECT   13    9   14   34   35
CONECT   14   13   15   16
CONECT   15   14
CONECT   16   14   36
CONECT   17    1
CONECT   18    1
CONECT   19    3
CONECT   20    3
CONECT   21    3
CONECT   22    4
CONECT   23    4
CONECT   24    5
CONECT   25    5
CONECT   26    5
CONECT   27    6
CONECT   28    6
CONECT   29    6
CONECT   30    8
CONECT   31   10
CONECT   32   11
CONECT   33   12
CONECT   34   13
CONECT   35   13
CONECT   36   16
MASTER        0    0    0    0    0    0    0    0   36    0   36    0
END`
};

// A simple component to display information about the current molecule
const MoleculeInfo = ({ name }: { name: string }) => {
  const info: Record<string, { description: string, usage: string }> = {
    caffeine: {
      description: 'Caffeine is a central nervous system stimulant that reduces fatigue and drowsiness.',
      usage: 'Found in coffee, tea, and many energy drinks. Used medically to stimulate the heart and also as a mild diuretic.'
    },
    aspirin: {
      description: 'Aspirin, also known as acetylsalicylic acid (ASA), is a medication used to reduce pain, fever, or inflammation.',
      usage: 'Used to treat pain, fever, and inflammation. Also used long-term to help prevent heart attacks, strokes, and blood clot formation.'
    },
    ibuprofen: {
      description: 'Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used for relieving pain, fever, and inflammation.',
      usage: 'Used to treat pain, tenderness, swelling, and stiffness caused by various conditions including osteoarthritis, rheumatoid arthritis, and menstrual cramps.'
    }
  };

  const currentInfo = info[name] || { description: 'No information available', usage: 'No usage information available' };

  return (
    <Box sx={{ mt: 2, p: 2, bgcolor: 'background.paper', borderRadius: 2 }}>
      <Typography variant="h6" gutterBottom>
        {name.charAt(0).toUpperCase() + name.slice(1)}
      </Typography>
      <Box sx={{ mb: 2 }}>
        <Typography variant="body1" component="span" sx={{ fontWeight: 'bold' }}>
          Description:
        </Typography>{' '}
        <Typography variant="body1" component="span">
          {currentInfo.description}
        </Typography>
      </Box>
      <Box>
        <Typography variant="body1" component="span" sx={{ fontWeight: 'bold' }}>
          Usage:
        </Typography>{' '}
        <Typography variant="body1" component="span">
          {currentInfo.usage}
        </Typography>
      </Box>
    </Box>
  );
};

// Main component for the Molecule Visualizer page
const MoleculeVisualizerPage: React.FC = () => {
  const [selectedMolecule, setSelectedMolecule] = useState<string>('caffeine');
  const [viewStyle, setViewStyle] = useState<'stick' | 'sphere' | 'line' | 'cartoon' | 'surface'>('stick');
  const [viewSize, setViewSize] = useState<{ width: number, height: number }>(getViewerSizePresets().medium);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Load 3DMol.js
  useEffect(() => {
    const load3DMolLibrary = async () => {
      setLoading(true);
      setError(null);

      try {
        const is3DMolLoaded = await load3DMol();

        if (!is3DMolLoaded) {
          setError('Failed to load 3DMol.js library. Please refresh the page and try again.');
        }
      } catch (err) {
        console.error('Error loading 3DMol.js:', err);
        setError('Error loading 3DMol.js library. Please refresh the page and try again.');
      } finally {
        setLoading(false);
      }
    };

    load3DMolLibrary();
  }, []);

  // Handler for molecule selection
  const handleMoleculeChange = (event: SelectChangeEvent) => {
    setSelectedMolecule(event.target.value);
  };

  // Handler for view style change
  const handleStyleChange = (style: 'stick' | 'sphere' | 'line' | 'cartoon' | 'surface') => {
    setViewStyle(style);
  };

  // Resize the viewer to a different size
  const handleResize = (size: 'small' | 'medium' | 'large' | 'extraLarge') => {
    setViewSize(getViewerSizePresets()[size]);
  };

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Typography variant="h4" component="h1" gutterBottom sx={{ color: 'primary.main', fontWeight: 'bold' }}>
        3D Molecule Visualizer
      </Typography>

      <Typography variant="body1" component="div" sx={{ mb: 4 }}>
        This interactive tool allows you to view and explore 3D models of different pharmaceutical molecules.
        Select a molecule and change the visualization style to better understand its structure.
      </Typography>

      {error && (
        <Alert severity="error" sx={{ mb: 4 }}>
          {error}
        </Alert>
      )}

      <Grid container spacing={4}>
        <Grid item xs={12} md={7}>
          <Paper elevation={3} sx={{ p: 3, borderRadius: 2, bgcolor: '#f5f5f5' }}>
            {loading ? (
              <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: viewSize.height }}>
                <CircularProgress />
              </Box>
            ) : (
              <MoleculeViewer
                molData={SAMPLE_MOLECULES[selectedMolecule as keyof typeof SAMPLE_MOLECULES]}
                format="pdb"
                style={viewStyle}
                width={viewSize.width}
                height={viewSize.height}
                className="molecule-viewer"
              />
            )}

            <Box sx={{ mt: 3, display: 'flex', justifyContent: 'center', flexDirection: 'column', gap: 2 }}>
              <Box component="div" sx={{ textAlign: 'center', typography: 'subtitle1' }}>
                Visualization Style
              </Box>
              <ButtonGroup variant="contained" aria-label="visualization style" sx={{ alignSelf: 'center' }}>
                <Button
                  onClick={() => handleStyleChange('stick')}
                  color={viewStyle === 'stick' ? 'primary' : 'inherit'}
                >
                  Stick
                </Button>
                <Button
                  onClick={() => handleStyleChange('sphere')}
                  color={viewStyle === 'sphere' ? 'primary' : 'inherit'}
                >
                  Sphere
                </Button>
                <Button
                  onClick={() => handleStyleChange('line')}
                  color={viewStyle === 'line' ? 'primary' : 'inherit'}
                >
                  Line
                </Button>
                <Button
                  onClick={() => handleStyleChange('cartoon')}
                  color={viewStyle === 'cartoon' ? 'primary' : 'inherit'}
                >
                  Cartoon
                </Button>
                <Button
                  onClick={() => handleStyleChange('surface')}
                  color={viewStyle === 'surface' ? 'primary' : 'inherit'}
                >
                  Surface
                </Button>
              </ButtonGroup>

              <Box component="div" sx={{ textAlign: 'center', typography: 'subtitle1', mt: 2 }}>
                Viewer Size
              </Box>
              <ButtonGroup variant="outlined" aria-label="viewer size" sx={{ alignSelf: 'center' }}>
                <Button
                  onClick={() => handleResize('small')}
                  color={viewSize.width === 400 ? 'primary' : 'inherit'}
                >
                  Small
                </Button>
                <Button
                  onClick={() => handleResize('medium')}
                  color={viewSize.width === 500 ? 'primary' : 'inherit'}
                >
                  Medium
                </Button>
                <Button
                  onClick={() => handleResize('large')}
                  color={viewSize.width === 600 ? 'primary' : 'inherit'}
                >
                  Large
                </Button>
              </ButtonGroup>
            </Box>
          </Paper>
        </Grid>

        <Grid item xs={12} md={5}>
          <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
            <CardContent>
              <Typography variant="h5" component="h2" gutterBottom sx={{ color: 'primary.main' }}>
                Molecule Selection
              </Typography>

              <FormControl fullWidth sx={{ mb: 4 }}>
                <InputLabel id="molecule-select-label">Select Molecule</InputLabel>
                <Select
                  labelId="molecule-select-label"
                  id="molecule-select"
                  value={selectedMolecule}
                  label="Select Molecule"
                  onChange={handleMoleculeChange}
                >
                  <MenuItem value="caffeine">Caffeine</MenuItem>
                  <MenuItem value="aspirin">Aspirin</MenuItem>
                  <MenuItem value="ibuprofen">Ibuprofen</MenuItem>
                </Select>
              </FormControl>

              <MoleculeInfo name={selectedMolecule} />

              <Box sx={{ mt: 4, p: 2, bgcolor: '#e8f5e9', borderRadius: 2 }}>
                <Typography variant="subtitle1" component="h3" gutterBottom sx={{ fontWeight: 'bold' }}>
                  Usage Instructions:
                </Typography>
                <Box component="div" sx={{ typography: 'body2' }}>
                  • Click and drag to rotate the molecule<br />
                  • Scroll to zoom in and out<br />
                  • Right-click and drag to translate<br />
                  • Double-click to center the view<br />
                  • Try different visualization styles to better understand the structure
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      <Box sx={{ mt: 8, p: 3, bgcolor: '#f5f5f5', borderRadius: 2 }}>
        <Typography variant="h5" component="h2" gutterBottom>
          About Molecular Visualization
        </Typography>
        <Typography variant="body1" component="div" sx={{ mb: 2 }}>
          Molecular visualization is an essential tool in drug discovery and development.
          It allows researchers to understand the 3D structure of molecules, which is crucial for
          predicting how they might interact with biological targets like proteins or enzymes.
        </Typography>
        <Typography variant="body1" component="div">
          By exploring the 3D structure of these drug molecules, you can gain insights into their
          function and how structural changes might affect their properties. This visualization
          capability is integrated with MedResAI's drug prediction platform, helping to interpret
          prediction results and understand suggested therapeutic compounds.
        </Typography>
      </Box>
    </Container>
  );
};

export default MoleculeVisualizerPage;